### ISSUE TITLE
Website https://blueprintui.dev is not readable with Safari 16.3

### ISSUE THREAD

**Issue by sven42** [blueprintui/layout#199]
Trying to read your documentation fails with Safari 16.3 (macOs Monterey). 

Compared with Chrome and Firefox, Safari 

- stops just before the animations and 
- the buttons "Start Building" and "Components" are missing.

Console logs many errors of this kind:
`TypeError: Illegal constructor`

Same is true for https://layout.blueprintui.dev which logs the same error is is completely blank.

**Comment by coryrylan** [comment]
Thanks for the feedback! I am redirecting the prior subdomain to the new consolidated docs here https://blueprintui.dev/docs/layout 

Safari works with a couple of polyfills added (ElementInternals, Constructible Style Sheets), however I am running into an issue with one of them causing a thread lockup atm. Once I figure this issue out I can enable them for Safari support.

**Comment by coryrylan** [comment]
Closing as latest Safari now supports ElementInternals as of 16.4
