### ISSUE TITLE
Addition of other breakpoints

### ISSUE THREAD

**Issue by acespace90** [blueprintui/layout#98]
**Is your feature request related to a problem? Please describe.**
In my case I need more than 4 breakpoints over sm, md, lg, xl

**Describe the solution you'd like**
I'd like to declare an array of custom breakpoints

Hi it would be great if there were the possibility of adding as many breakpoints as you want and then automatically generate the columns.

For example in my case I have these breakpoints

```
xsmall : 375px,
small  : 428px,
medium : 748px,
large  : 1024px,
xlarge : 1280px,
2xlarge: 1536px,
3xlarge: 1920px
```

But currently I only can use 4 of these

**Comment by coolemur** [comment]
Also, customising existing breakpoints would be nice.

For example, if you have different breakpoints in your project than defined in blueprintcss.

**Comment by coryrylan** [comment]
Thanks for the feedback! Yes this has been a frustrating limitation for blueprint layouts for a while now due to some limitations of CSS vars/media queries and dynamic attribute values. I'm hoping to make it easy to generate custom builds for custom breakpoints and values soon.
